"""
Mapeamento Composio tool slug → uso no BAI CRM Auditor.

Docs toolkit: https://v3.docs.composio.dev/toolkits/kommo
Execução HTTP: POST {COMPOSIO_EXECUTE_BASE_URL}/tools/execute/{slug}
"""
from __future__ import annotations

# Leitura — alinhado ao sync_service (normalização em mapper.py)
LIST_PIPELINES = "KOMMO_LIST_LEADS_PIPELINES"
LIST_PIPELINE_STAGES = "KOMMO_LIST_PIPELINE_STAGES"
LIST_USERS = "KOMMO_LIST_USERS"
LIST_LEADS = "KOMMO_LIST_LEADS"
LIST_CONTACTS = "KOMMO_LIST_CONTACTS"
LIST_COMPANIES = "KOMMO_LIST_COMPANIES"
LIST_TASKS = "KOMMO_LIST_TASKS"
LIST_CUSTOM_FIELDS = "KOMMO_LIST_CUSTOM_FIELDS"
LIST_SOURCES = "KOMMO_LIST_SOURCES"
LIST_LOSS_REASONS = "KOMMO_LIST_LOSS_REASONS"
LIST_ENTITY_NOTES = "KOMMO_LIST_ENTITY_NOTES"
LIST_EVENTS = "KOMMO_LIST_EVENTS"
LIST_CONVERSATIONS = "KOMMO_LIST_CONVERSATIONS"
