-- Customer Health Hub tables
-- Tracks composite health score and proactive alerts per customer

-- ── customer_health_scores ────────────────────────────────────────────────────
create table if not exists public.customer_health_scores (
  id                 uuid primary key default gen_random_uuid(),
  org_id             uuid not null references public.organizations(id) on delete cascade,
  customer_key       text not null,
  customer_name      text,
  customer_email     text,
  source_table       text,

  -- Composite score (0-100)
  health_score       integer not null default 0 check (health_score between 0 and 100),
  health_band        text not null default 'indefinido', -- saudavel | atencao | risco | critico

  -- Component scores (each 0-100, used to compute composite)
  engagement_score   integer not null default 0,  -- recency + frequency of activities
  revenue_score      integer not null default 0,  -- monetary trend
  momentum_score     integer not null default 0,  -- pipeline deals open/moving
  loyalty_score      integer not null default 0,  -- tenure + RFM segment

  -- Delta vs previous period
  health_delta       integer,   -- positive = improving, negative = declining
  trend              text,      -- up | stable | down

  -- Signals that triggered the score
  signals            jsonb not null default '[]'::jsonb, -- [{type, label, severity}]

  calculated_at      timestamptz not null default now(),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (org_id, customer_key)
);

alter table public.customer_health_scores enable row level security;
create policy "org members can read health scores"
  on public.customer_health_scores for select
  using (org_id in (select org_id from public.profiles where id = auth.uid()));

create index if not exists customer_health_org_band_idx
  on public.customer_health_scores (org_id, health_band);
create index if not exists customer_health_org_score_idx
  on public.customer_health_scores (org_id, health_score desc);

create trigger update_customer_health_scores_updated_at
  before update on public.customer_health_scores
  for each row execute function public.update_updated_at_column();

-- ── customer_alerts ───────────────────────────────────────────────────────────
-- Proactive alerts generated by the health engine
create table if not exists public.customer_alerts (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references public.organizations(id) on delete cascade,
  customer_key     text not null,
  customer_name    text,
  alert_type       text not null, -- churn_risk | no_activity | deal_stalled | revenue_drop | champion_at_risk
  severity         text not null default 'info', -- critical | warning | info
  title            text not null,
  description      text not null default '',
  metadata         jsonb not null default '{}'::jsonb, -- extra context (days_since_activity, etc.)
  acknowledged     boolean not null default false,
  acknowledged_at  timestamptz,
  acknowledged_by  uuid references auth.users(id),
  resolved         boolean not null default false,
  resolved_at      timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

alter table public.customer_alerts enable row level security;
create policy "org members can manage alerts"
  on public.customer_alerts for all
  using (org_id in (select org_id from public.profiles where id = auth.uid()));

create index if not exists customer_alerts_org_severity_idx
  on public.customer_alerts (org_id, severity, resolved, created_at desc);
create index if not exists customer_alerts_org_customer_idx
  on public.customer_alerts (org_id, customer_key, resolved);

create trigger update_customer_alerts_updated_at
  before update on public.customer_alerts
  for each row execute function public.update_updated_at_column();

-- ── customer_activity_timeline ────────────────────────────────────────────────
-- Unified timeline of all customer touchpoints (CRM activities + deals + alerts)
create table if not exists public.customer_activity_timeline (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references public.organizations(id) on delete cascade,
  customer_key     text not null,
  event_type       text not null, -- crm_activity | deal_update | health_change | alert | note
  event_subtype    text,          -- call | email | note | stage_change | etc.
  title            text not null,
  description      text,
  happened_at      timestamptz not null,
  metadata         jsonb not null default '{}'::jsonb,
  source           text,          -- "kommo" | "hubspot" | "manual" | "system"
  created_at       timestamptz not null default now()
);

alter table public.customer_activity_timeline enable row level security;
create policy "org members can read customer timeline"
  on public.customer_activity_timeline for select
  using (org_id in (select org_id from public.profiles where id = auth.uid()));

create index if not exists customer_timeline_org_customer_idx
  on public.customer_activity_timeline (org_id, customer_key, happened_at desc);
